webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    title = 'settings'
    return render_template('admin/index.html', page_title=title)

webapp/news/views.py
from flask import abort, Blueprint, render_template, current_app, flash, redirect, request, url_for
from flask_login import current_user, login_required

from webapp import db
from webapp.news.models import News, Comments
from webapp.weather import weather_by_city
from webapp.news.forms import CommentForm
from webapp.utils import get_redirect_target


blueprint = Blueprint('news', __name__)


@blueprint.route('/')
def index():
    title = 'News hoho'
    weather = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
    news_lists = News.query.filter(News.text.isnot(None)).order_by(News.published.desc()).all()
    return render_template('news/index.html', page_title=title, weather=weather, news_lists=news_lists)


@blueprint.route('/news/<int:news_id>')
def single_news(news_id):
    my_news = News.query.filter(News.id == news_id).first()
    comment_form = CommentForm(news_id=my_news.id)
    if not my_news:
        abort(404)

    return render_template('news/single_news.html', page_title=my_news.title,
                           comment_form=comment_form, news=my_news)


@blueprint.route('/news/comment', methods=['POST'])
@login_required
def add_comment():
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comments(text=form.comment_text.data, news_id=form.news_id.data,
                           user_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Комментарий добавлен')
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в заполнении поля "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
    return redirect(get_redirect_target())

webapp/user/views.py
from flask import render_template, Blueprint, flash, redirect, url_for
from flask_login import login_user, logout_user, current_user

from webapp import db
from webapp.user.models import User
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.utils import get_redirect_target

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())
    title = 'Sign in'
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash(f'Hello {user.username}')
            return redirect(get_redirect_target())
    flash('Wrong username or password')
    return redirect(url_for('user.login'))


@blueprint.route('/registration')
def registration():
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    title = 'Sign up'
    registration_form = RegistrationForm()
    return render_template('user/registration.html', page_title=title, form=registration_form)


@blueprint.route('/registration-login', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Successful registration')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('error in field "{}" - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.registration'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Logout')
    return redirect(url_for('news.index'))

webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet"
    href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/atom-one-dark.min.css">

    <title>{{ page_title }}</title>
  </head>
  <body>
    {% include "menu.html" %}
    <div class="container">
        <h1>{{ page_title }}</h1>
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container">
        <h1>{{ page_title }}</h1>
        <div class="row">
            <div class="col-8">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-warning" role="alert">
                        {% for message in messages %}
                            {{ message }}<br>
                        {% endfor %}
                    </div>
                    {% endif %}
                {% endwith %}
                <h2>{{ News }}</h2>
                {% for news in news_lists %}
                <h3><a href="{{ news.url }}" >{{ news.title }}</a></h3>
                <p>{{ news.published.strftime('%d.%m.%Y') }}</p>
                <hr>
                {% endfor %}
            </div>
            <div class="col-4">
                <h2>Weather forecast</h2>
                {% if weather %}
                    Weather in Moscow {{ weather.temp_C }}, feel like {{ weather.FeelsLikeC }}
                {% else %}
                    Weather service not responding
                {% endif %}
            </div>
        </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Python news</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('news.index') }}">Home</a>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav">
      </li>
      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <span class="nav-link">Hello {{ current_user.username }}!</span>
      </li>
        {% if current_user.is_admin %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Admin panel</a>
        </li>
        {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.login') }}">Sign In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.registration') }}">Registration</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}